platform :ios,'6.0'
pod 'Nimbus', '~> 1.2.0'
pod 'AFNetworking', '~> 2.2.3'
pod 'MBProgressHUD', '~> 0.8'
pod 'MTStatusBarOverlay', '~> 0.9.1'
pod 'SSKeychain', '~> 1.2.2'
pod 'HPGrowingTextView', '~> 1.1'
pod 'SDSegmentedControl', '~> 1.0.2'
pod 'LTUpdate', '~> 0.0.2'
pod 'JSCustomBadge', '~> 1.0.1'
pod 'FlatUIKit', '~> 1.4'
pod 'SDWebImage', '~> 3.7.1'